"""add_cascade_delete_to_user_relationships

Revision ID: 16e95d90b231
Revises: dd5cc0f3c745
Create Date: 2025-05-01 07:08:12.266168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16e95d90b231'
down_revision: Union[str, None] = 'dd5cc0f3c745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop existing foreign keys
    op.drop_constraint('websites_user_id_fkey', 'websites')
    op.drop_constraint('gsc_page_data_user_id_fkey', 'gsc_page_data')
    op.drop_constraint('gsc_keyword_data_user_id_fkey', 'gsc_keyword_data')
    op.drop_constraint('crawler_results_user_id_fkey', 'crawler_results')
    op.drop_constraint('page_optimizations_user_id_fkey', 'page_optimizations')

    # Create new foreign keys with CASCADE
    op.create_foreign_key('websites_user_id_fkey', 'websites', 'users', 
                         ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('gsc_page_data_user_id_fkey', 'gsc_page_data', 'users', 
                         ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('gsc_keyword_data_user_id_fkey', 'gsc_keyword_data', 'users', 
                         ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('crawler_results_user_id_fkey', 'crawler_results', 'users', 
                         ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('page_optimizations_user_id_fkey', 'page_optimizations', 'users', 
                         ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('websites_user_id_fkey', 'websites')
    op.drop_constraint('gsc_page_data_user_id_fkey', 'gsc_page_data')
    op.drop_constraint('gsc_keyword_data_user_id_fkey', 'gsc_keyword_data')
    op.drop_constraint('crawler_results_user_id_fkey', 'crawler_results')
    op.drop_constraint('page_optimizations_user_id_fkey', 'page_optimizations')

    # Recreate foreign keys without CASCADE
    op.create_foreign_key('websites_user_id_fkey', 'websites', 'users', 
                         ['user_id'], ['id'])
    op.create_foreign_key('gsc_page_data_user_id_fkey', 'gsc_page_data', 'users', 
                         ['user_id'], ['id'])
    op.create_foreign_key('gsc_keyword_data_user_id_fkey', 'gsc_keyword_data', 'users', 
                         ['user_id'], ['id'])
    op.create_foreign_key('crawler_results_user_id_fkey', 'crawler_results', 'users', 
                         ['user_id'], ['id'])
    op.create_foreign_key('page_optimizations_user_id_fkey', 'page_optimizations', 'users', 
                         ['user_id'], ['id'])
    # ### end Alembic commands ###
