"""add keywords and sources to page optimizations

Revision ID: dd5cc0f3c745
Revises: f12c65a3d9cd
Create Date: 2025-04-21 16:58:23.312727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd5cc0f3c745'
down_revision: Union[str, None] = 'f12c65a3d9cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_optimizations', sa.Column('keywords_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('page_optimizations', sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_optimizations', 'sources')
    op.drop_column('page_optimizations', 'keywords_used')
    # ### end Alembic commands ###
