"""add_updated_at_to_gsc_tables

Revision ID: f09b5dfdc8df
Revises: clean_gsc
Create Date: 2025-03-27 21:51:23.002912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f09b5dfdc8df'
down_revision: Union[str, None] = 'clean_gsc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsc_keyword_data', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('gsc_page_data', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gsc_page_data', 'last_updated')
    op.drop_column('gsc_keyword_data', 'last_updated')
    # ### end Alembic commands ###
