version: '3.8'

services:
  backend:
    build: .
    container_name: tothetop_backend
    restart: always
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    ports:
      - "8000:8000"
    networks:
      - tothetop_network

networks:
  tothetop_network:
    external: true